---
title: "Main Demo"
author: "Ali Taqi"
date: "2/17/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RMAT)
library(tidyverse)
```

```{r}
#=================================================================================#
#                           EIGENVALUE SPECTRUM (PARALLEL)
#=================================================================================#

#' @title Obtain the eigenvalue spectrum of a matrix or ensemble of matrices concurrently (faster).
#' @description Returns a tidied dataframe of the eigenvalues of a random matrix or ensemble concurrently (faster).
#' 
#' @inheritParams spectrum
#' 
#' @return A tidy dataframe with the real & imaginary components of the eigenvalues and their norms along with a unique index.
#' 
#' @examples
#' # Generate a random matrix 
#' P <- RME_norm(N = 100, size = 500)
#' # Compute the spectrum concurrently (faster)
#' spec_P <- spectrum_par(P)
#' 
spectrum_par <- function(array, components = TRUE, sort_norms = TRUE, singular = FALSE, order = NA){
  # Digits to round values to
  digits <- 4
  # Set up futures
  future::plan(multisession)
  # Get the type of array
  array_class <- .arrayClass(array)
  # Compute the spectrum
  if(array_class == "ensemble") {
    # Array is an ensemble; recursively row bind each matrix's eigenvalues  
    furrr::future_map_dfr(array, .spectrum_matrix, components, sort_norms, singular, order, digits)
  } 
  else if(array_class == "matrix"){
    # Array is a matrix; call function returning eigenvalues for a singleton matrix
    .spectrum_matrix(array, components, sort_norms, singular, order, digits)
  }
}

```


```{r}
# Eigenvalue dispersion in parallel
P <- RME_norm(N = 50, size = 20)
disp_P <- dispersion_par(P)
```

```{r}
ens <- RME_norm(5, size = 2)
length(ens)
elem_ens <- ens[[1]]
P <- RM_norm(5, cplx = TRUE)
length(P)
elem_P <- P[[1]]
class(elem_P)
"matrix" %in% class(elem_ens)
sum(c("numeric","complex") %in% class(elem_P))
```

```{r}
.arrayClass(P)
```


```{r}
N <- 5
purrr::map_dfr(2:N, function(i){data.frame(i = i, j = i - 1)})
```

