---
title: "Tests"
author: "Ali Taqi"
date: "2/19/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RMAT)
source("../R/matrices-diagnostics.R")
source("../R/matrices.R")
```



```{r}
#test ideas
normal_mean <- function(N, mu = 0, threshold = 0.25){
  P <- RM_norm(N = 5, mean = mu)
  mu_sim <- .normal_params(P)[[1]]
  abs(mu - mu_sim) < threshold
}

repl <- 10000
sum(replicate(repl, normal_mean(200, mu = 5, threshold = 0.2), TRUE))/repl
```
```{r}
normal_sd <- function(N, sd = 1, threshold = 0.25){
  P <- RM_norm(N = 5, mean = 0, sd = sd)
  sd_sim <- .normal_params(P)[[2]]
  abs(sd - sd_sim) < threshold
}

repl <- 10000
sum(replicate(repl, normal_sd(200, sd = 1, threshold = 0.2), TRUE))/repl
```
```{r}
stoch_test <- function(N, size, b = F){
  v <- do.call("rbind",lapply(X = RME(RM_stoch, args = c(N = N, symm = T, sparsity = b), size), FUN = .isStochastic))
  sum(v)/size
  }
#map(.x = RME(RM_stoch, args = c(N = 5, symm = T), 10), .f = .isStochastic)

stoch_test(3,1000)
stoch_test(5,1000,T)
```

